# Generated by Django 5.0.7 on 2024-07-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
